// get all goals
GET http://localhost:5000/api/goals
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMTAyYjVlY2E3ODE0ZDJkNGEzMDVlOCIsImlhdCI6MTY0NTIyODM0MiwiZXhwIjoxNjQ3ODIwMzQyfQ.reqdXmg_IPxRBspWrTYUydbOE4qg7ommj_7jnr2bSOY

text=This is Buğras goal 1

###

// create goal
POST http://localhost:5000/api/goals
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMTAyYjVlY2E3ODE0ZDJkNGEzMDVlOCIsImlhdCI6MTY0NTIyODM0MiwiZXhwIjoxNjQ3ODIwMzQyfQ.reqdXmg_IPxRBspWrTYUydbOE4qg7ommj_7jnr2bSOY

text=My Second Goal

###

// update goal
PUT http://localhost:5000/api/goals/62094a403d756620de3f738c
Content-Type: application/x-www-form-urlencoded

text=Updated Goal

###

// delete goal
DELETE http://localhost:5000/api/goals/62094a403d756620de3f738c
Content-Type: application/x-www-form-urlencoded

###

// register user
POST http://localhost:5000/api/users
Content-Type: application/x-www-form-urlencoded

name=Buğra&email=b@g.com&password=123456

###

// authenticate user
POST http://localhost:5000/api/users/login
Content-Type: application/x-www-form-urlencoded

email=b@g.com&password=123456

###

// get user
GET http://localhost:5000/api/users/me
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMTAyYjVlY2E3ODE0ZDJkNGEzMDVlOCIsImlhdCI6MTY0NTIyODM0MiwiZXhwIjoxNjQ3ODIwMzQyfQ.reqdXmg_IPxRBspWrTYUydbOE4qg7ommj_7jnr2bSOY

email=b@g.com&password=123456

###
