### signup
### "productKey": "$2a$10$YptSjFvZxDHDcJGeOMgboe.6l.K7cSHLyZa1AUNRyfG4ISpoanS8i"
POST http://localhost:3000/auth/signup/BUYER
Content-Type: application/json

{
  "name": "Buyer",
  "phone": "(555) 555 5555",
  "email": "buyer@gmail.com",
  "password": "banana"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "realtor@gmail.com",
  "password": "banana"
}

### generate product key
POST http://localhost:3000/auth/key
Content-Type: application/json

{
  "email": "realtor@gmail.com",
  "userType": "REALTOR"
}

### get me
GET http://localhost:3000/auth/me
Content-Type: application/json

