### get homes
GET http://localhost:3000/home?city=Toronto&minPrice=1500000&maxPrice=3000000&propertyType=RESIDENTIAL
Content-Type: application/json

### get home by id
GET http://localhost:3000/home/1
Content-Type: application/json

### create home
POST http://localhost:3000/home
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnV5ZXIiLCJpZCI6MTEsImlhdCI6MTY5MzU3OTQ1NywiZXhwIjoxNjk3MTc5NDU3fQ.3W9M8rxDNFwzzMAgTFawgQIHcxLnDaxbiwerWOzHjl8

{
  "numberOfBedrooms": 4,
  "numberOfBathrooms": 5,
  "address": "1111 Axe Ave",
  "city": "Dallas",
  "price": 500000,
  "landSize": 3500,
  "propertyType": "CONDO",
  "images": [
    {
      "url": "img10"
    },
    {
      "url": "img11"
    }
  ]
}

### update home by id
PUT http://localhost:3000/home/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnV5ZXIiLCJpZCI6MTEsImlhdCI6MTY5MzU3OTYyNCwiZXhwIjoxNjk3MTc5NjI0fQ.VhN6PXj05jJFrUnYNSF_jmOSpDMp6_q64We8ehXWILM

{
  "city": "Houston"
}

### delete home by id
DELETE http://localhost:3000/home/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnV5ZXIiLCJpZCI6MTEsImlhdCI6MTY5MzU3OTQ1NywiZXhwIjoxNjk3MTc5NDU3fQ.3W9M8rxDNFwzzMAgTFawgQIHcxLnDaxbiwerWOzHjl8

### inquire
POST http://localhost:3000/home/11/inquire
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnV5ZXIiLCJpZCI6MTEsImlhdCI6MTY5MzY5MTk1MCwiZXhwIjoxNjk3MjkxOTUwfQ.PkuExIKiWAnwnxR1qkZPPWYnrmfUXhX_QSBzVYzPCK8

{
  "message": "I really like this house!"
}

### view all messages
GET http://localhost:3000/home/11/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmVhbHRvciIsImlkIjoxMCwiaWF0IjoxNjkzNjkyMTA4LCJleHAiOjE2OTcyOTIxMDh9.uNFKljTetq_vFIN5okOsV0ZzKSzw9xwNz8GfeF62iK0
