### Get all entries
GET http://localhost:3001/entries/all


### Create new entry
POST http://localhost:3001/entries/create
Content-Type: application/json

{
  "name": "Buğra Otken",
  "phoneNumber": "05357291820"
}

### Update an entry
PATCH http://localhost:3001/entries/update/6103cf021c9bcf03006f4f8b
Content-Type: application/json

{
  "name": "Burcu Otken",
  "phoneNumber": "05422135678"
}

### Delete an entry
DELETE http://localhost:3001/entries/delete/6103ced8ce035b0e8c66f7b3
