// get rules
GET http://localhost:3001/api/rules/getRules

###

// get specific rule
GET http://localhost:3001/api/rules/getRule/16

###

// create rule
POST http://localhost:3001/api/rules/createRule
Content-Type: application/json

{
  "username": "aaa",
  "password": "bbb",
  "email": "ccc@kkk",
  "phone_number": "ddd",
  "name": "eee",
  "surname": "fff"
}

###

// edit rule
POST http://localhost:3001/api/rules/editRule/16
Content-Type: application/json

{
  "username": "12ktdtud3",
  "password": "dhfds",
  "email": "ccjjugdc",
  "phone_number": "ddkutdutkddd",
  "name": "eekdktde",
  "surname": "fkdkdkff"
}

###

// delete rule
POST http://localhost:3001/api/rules/deleteRule/14
Content-Type: application/json

###
