// get rules
GET http://localhost:3001/api/rules/getall

###

// get specific rule
GET http://localhost:3001/api/rules/getone/1

###

// create rule
POST http://localhost:3001/api/rules/create
Content-Type: application/json

{
  "source": "Sel",
  "min_value": "45.7",
  "max_value": "93.5",
  "warning_message": "Sel felaketi geliyor. Dikkatli olun.",
  "groups": "3,4,8"
}

###

// edit rule
POST http://localhost:3001/api/rules/edit/2
Content-Type: application/json

{
  "source": "Sel",
  "min_value": "20.45",
  "max_value": "34.98",
  "warning_message": "Sel felaketi geliyor. Dikkatli olun.",
  "groups": "3,4,8"
}

###

// delete rule
POST http://localhost:3001/api/rules/delete/1
Content-Type: application/json

###
