// get users
GET http://localhost:3001/api/users/getall

###

// get specific user
GET http://localhost:3001/api/users/getone/16

###

// create user
POST http://localhost:3001/api/users/create
Content-Type: application/json

{
"username": "aaa",
"password": "bbb",
"email": "ccc@kkk",
"phone_number": "ddd",
"name": "eee",
"surname": "fff"
}

###

// edit user
POST http://localhost:3001/api/users/edit/16
Content-Type: application/json

{
"username": "12ktdtud3",
"password": "dhfds",
"email": "ccjjugdc",
"phone_number": "ddkutdutkddd",
"name": "eekdktde",
"surname": "fkdkdkff"
}

###

// delete user
POST http://localhost:3001/api/users/delete/14
Content-Type: application/json

###
