### signup
POST http://localhost:3000/auth/signup/REALTOR
Content-Type: application/json

{
  "name": "Bugra",
  "phone": "(555) 555 5555",
  "email": "bo4@gmail.com",
  "password": "banana",
  "productKey": "$2a$10$IS0FEkxKqqRwB6/LbdhBieYXR0iva1MoV.34L2wLODn78DD.gGP/e"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "bo2@gmail.com",
  "password": "banana"
}

### generate product key
POST http://localhost:3000/auth/key
Content-Type: application/json

{
  "email": "bo4@gmail.com",
  "userType": "REALTOR"
}
