services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src
