// get rules
GET http://localhost:3001/api/rules/getall

###

// get specific rule
GET http://localhost:3001/api/rules/getone/1

###

// create rule
POST http://localhost:3001/api/rules/create
Content-Type: application/json

{
  "source": "precipitation",
  "min_value": "45.7",
  "max_value": "93.5",
  "is_present": true
}

###

// edit rule
POST http://localhost:3001/api/rules/edit/2
Content-Type: application/json

{
  "source": "precipitation",
  "min_value": "45.7",
  "max_value": "93.5",
  "is_present": true
}

###

// delete rule
POST http://localhost:3001/api/rules/delete/1
Content-Type: application/json

###
