// get users
GET http://localhost:3001/api/users/getall

###

// get specific user
GET http://localhost:3001/api/users/getone/16

###

// create user
POST http://localhost:3001/api/users/create
Content-Type: application/json

{
  "username": "07102021",
  "password": "07102021",
  "email": "07102021@gmail.com",
  "phone_number": "07102021",
  "name": "07102021",
  "surname": "07102021",
  "is_admin": false,
  "poi_responsibilities": "{1,2,3}",
  "warnings_to_receive": "{3,4,5}"
}

###

// edit user
POST http://localhost:3001/api/users/edit/44
Content-Type: application/json

{
  "username": "07102021",
  "password": "07102021",
  "email": "07102021@gmail.com",
  "phone_number": "07102021",
  "name": "07102021",
  "surname": "07102021",
  "is_admin": false,
  "poi_responsibilities": "{1,2,3}",
  "warnings_to_receive": "{3,4,5}"
}

###

// delete user
POST http://localhost:3001/api/users/delete/14
Content-Type: application/json

###
