// get messages
GET http://localhost:3001/api/warnings/getall

###

// get specific message
GET http://localhost:3001/api/warnings/getone/1

###

// create message
POST http://localhost:3001/api/warnings/create
Content-Type: application/json

{
  "source": "yağmur",
  "event": "orta şiddetli",
  "message": "dikkat edin",
  "is_screen": true,
  "is_field": false,
  "rules": "{1,2,3}"
}

###

// edit message
POST http://localhost:3001/api/warnings/edit/1
Content-Type: application/json

{
  "source": "yağmur",
  "event": "orta şiddetli",
  "message": "dikkat edin",
  "is_screen": true,
  "is_field": false,
  "rules": "{1,2,3,4,5}"
}

###

// delete message
POST http://localhost:3001/api/warnings/delete/2
Content-Type: application/json

###
