version: "3.1"

# MongoDB, Postgres, Redis, Elasticsearch, Kibana, MySql, Postgres
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
