### GET request to example server
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###

GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjMiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUwOTM2OTM4LCJleHAiOjE3NTA5NDA1Mzh9.uiq54g3jVm-uasv1r_55xN06X26NpKEP3b_M4PMW08I

###
