POST http://localhost:3001/layer?layer=bina&filter=id_mahalle=2
Accept: application/json

###


POST http://localhost:3001/unique?layer=bina&field=id_mahalle
Accept: application/json

###


POST http://localhost:3001/fields?layer=bina
Accept: application/json

###