version: "3.8"
services:
  backend:
#    image: antoniopapa1991/admin-backend
    image: antoniopapa1991/influencer-backend
    environment:
      DB_HOST: db
#      DB_DATABASE: admin
      DB_DATABASE: influencer
      DB_USERNAME: root
      DB_PASSWORD: root
      CHECKOUT_URL: http://localhost:3000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    environment:
#      MYSQL_DATABASE: admin
      MYSQL_DATABASE: influencer
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
    - .dbdata:/var/lib/mysql