/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosNewIndexRouteImport } from './routes/todos/new/index'
import { Route as TodosIdEditIndexRouteImport } from './routes/todos/$id/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosNewIndexRoute = TodosNewIndexRouteImport.update({
  id: '/todos/new/',
  path: '/todos/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIdEditIndexRoute = TodosIdEditIndexRouteImport.update({
  id: '/todos/$id/edit/',
  path: '/todos/$id/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos/new/': typeof TodosNewIndexRoute
  '/todos/$id/edit/': typeof TodosIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos/new': typeof TodosNewIndexRoute
  '/todos/$id/edit': typeof TodosIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/todos/new/': typeof TodosNewIndexRoute
  '/todos/$id/edit/': typeof TodosIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todos/new/' | '/todos/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos/new' | '/todos/$id/edit'
  id: '__root__' | '/' | '/todos/new/' | '/todos/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodosNewIndexRoute: typeof TodosNewIndexRoute
  TodosIdEditIndexRoute: typeof TodosIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/new/': {
      id: '/todos/new/'
      path: '/todos/new'
      fullPath: '/todos/new/'
      preLoaderRoute: typeof TodosNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$id/edit/': {
      id: '/todos/$id/edit/'
      path: '/todos/$id/edit'
      fullPath: '/todos/$id/edit/'
      preLoaderRoute: typeof TodosIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodosNewIndexRoute: TodosNewIndexRoute,
  TodosIdEditIndexRoute: TodosIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
