### GET all workouts
GET http://localhost:4000/api/workouts
Content-Type: application/json

### GET a single workout
GET http://localhost:4000/api/workouts/62b41f41155c378dd9c8792d
Content-Type: application/json

### CREATE a workout
POST http://localhost:4000/api/workouts
Content-Type: application/json

{
  "title": "Bench press",
  "load": 25,
  "reps": 40
}

### DELETE a workout
DELETE http://localhost:4000/api/workouts/62b41f41155c378dd9c8792d
Content-Type: application/json

### UPDATE a workout
PATCH http://localhost:4000/api/workouts/62b41f41155c378dd9c8792d
Content-Type: application/json

{
  "reps": 50
}

### GET all workouts
GET http://localhost:4000/api/workouts
Content-Type: application/json

### LOGIN user
POST http://localhost:4000/api/user/login
Content-Type: application/json

{
  "email": "bugra@gmail.com",
  "password": "abc"
}

### SIGNUP user
POST http://localhost:4000/api/user/signup
Content-Type: application/json

{
  "email": "luigi@netninja.dev",
  "password": "ABCabs123!"
}
